openapi: 3.0.0
info:
  version: '0.1.0'
  title: 'houseportal-backend'
  license:
    name: MIT
servers:
  - url: 'localhost:3000'
paths:
  /login:
    post:
      summary: 'Login endpoint: Generates a new bearer for the user'
      operationId: loginUser
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginData'

        
      responses:
        '200':
          description: 'Login response: User token and bearer'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /register:
    post:
      summary: 'Create an account endpoint: A function that registers a new user'
      operationId: createUser
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountData'
      responses:
            '200':
                description: 'Login response: User token and bearer'
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Session'                  
            default:
                description: Unexpected error
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Error'
  /logout:
      post:
        summary: 'Logs out the user: Logs out the user'
        operationId: : logs out
        tags:
           - user
        requestBody:
            required: false
        headers:
            Autorization:
                description: Send the bearer to deconnect
                schema:
                    type: string
                
            
        responses:
            

        

    

            

    


components:
  schemas:
    AccountData:
        type: object
        required:
            - username
        properties:
            username:
                type: string
    LoginData:
      type: object
      required:
        - id
        - pwd
      properties:
        id:
          type: string
        pwd:
          type: string
    Session:
      type: object
      required:
        - bearer
        - token
      properties:
        bearer:
          type: string
        token:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []