name: Deploy

on:
  push:
    branches:
      - main  # Push to main branch
      - ci-cd/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
        
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      
      - name: Run tests with Gradle
        run: |
          ./gradlew test

  publish:
    runs-on: "ubuntu-latest"
    needs: test
    if: "contains(github.event.head_commit.message, 'trigger-cd') || contains(github.event.head_commit.message, 'Merge & deploy')"

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Generate war
        run: |
          ./gradlew war

      - name: Build images
        run: |
          docker build -t ghcr.io/photonsquid/houseportal-backend .

      - name: Login to GitHub Packages
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          echo ${{ env.TOKEN }} | docker login ghcr.io -u photonsquid --password-stdin

      - name: Push to GitHub Packages
        id: push-to-gh-packages
        run: |
          tag=$(git rev-parse --short HEAD)
          docker tag ghcr.io/photonsquid/houseportal-backend ghcr.io/photonsquid/houseportal-backend:$tag
          docker push ghcr.io/photonsquid/houseportal-backend:$tag
          echo ::set-output name=tag::$tag
      
      - name: Logout
        run: |
          docker logout
      
      - name: Create commit comment
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            ## Summary
            ✅ Commit successfully deployed to GitHub packages.
            🔗 Commit reference: `${{ github.sha }}`
            📦 Deployed image tag: `${{ steps.push-to-gh-packages.outputs.tag }}`

            _This message was automatically generated by an action workflow._
    